### ISSUE TITLE
As a user I should be able to share the vendor on social network(fb, Twitter, Google+)

### ISSUE THREAD

**Issue by salmaadel** [ranaalaa/Bride-website#47]

**Comment by salmaadel** [comment]
@HananGhannam  @ranaalaa

**Comment by ranaalaa** [comment]
@salmaadel I checked the scenario for sharing twitter and google+ are fine, but I think there is a problem with facebook, it doesn't refer to the link I shared 
please have a look

**Comment by salmaadel** [comment]
@ranaalaa  I resolved the scenrio issues

**Comment by ranaalaa** [comment]
@salmaadel good job (Y)

**Comment by salmaadel** [comment]
@Mayada77 review UML

**Comment by Mayada77** [comment]
Done ya salma ya amr :dancer:

**Comment by Mayada77** [comment]
@salmaadel  SALOMA i couldn't find the wireframes

**Comment by salmaadel** [comment]
@Mayada77 ouh dear, I fixed the problem ;) (Y)

**Comment by Mayada77** [comment]
@salmaadel mashy ya amr
