### ISSUE TITLE
As a user, I should to view certain number of items per page. 

### ISSUE THREAD

**Issue by DoniaMourad** [ranaalaa/Bride-website#48]
branch name Items

**Comment by DoniaMourad** [comment]
@HananGhannam  code review

**Comment by DoniaMourad** [comment]
@ranaalaa  scenario review

**Comment by DoniaMourad** [comment]
@Jala-Ashraf review documentation

**Comment by ranaalaa** [comment]
@DoniaMourad index dress needs fixing

**Comment by DoniaMourad** [comment]
@salmaadel  review test

**Comment by DoniaMourad** [comment]
@Mayada77 review UMLLL

**Comment by DoniaMourad** [comment]
@ranaalaa fixed review the scenario again

**Comment by ranaalaa** [comment]
@DoniaMourad bravoo dodoo :100: :+1:
