### ISSUE TITLE
As a user, I should be able to sort by name and price

### ISSUE THREAD

**Issue by DoniaMourad** [ranaalaa/Bride-website#53]
Branch name Sort

**Comment by DoniaMourad** [comment]
@HananGhannam  Please review my code (a)

**Comment by DoniaMourad** [comment]
@ranaalaa review scenario please

**Comment by DoniaMourad** [comment]
@Jala-Ashraf review documentation

**Comment by Jala-Ashraf** [comment]
@DoniaMourad  Done reviewing documentation

**Comment by ranaalaa** [comment]
@DoniaMourad  done

**Comment by DoniaMourad** [comment]
@salmaadel Review test

**Comment by salmaadel** [comment]
@DoniaMourad  done

**Comment by DoniaMourad** [comment]
@Mayada77  review UML :**********
